name: Deploy Next.js site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTACT_EMAIL: ${{ vars.CONTACT_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace email placeholders
        run: |
          EMAIL="${{ vars.CONTACT_EMAIL || 'muhammadhaziq341@gmail.com' }}"
          echo "=== Environment Variable Debug Info ==="
          echo "CONTACT_EMAIL from vars: ${{ vars.CONTACT_EMAIL }}"
          echo "Final email to use: $EMAIL"
          
          echo "=== Replacing email placeholders ==="
          # Replace in README.md
          if [ -f "README.md" ]; then
            echo "Processing README.md..."
            PLACEHOLDER_COUNT=$(grep -o "DYNAMIC_EMAIL_PLACEHOLDER" README.md | wc -l)
            echo "Found $PLACEHOLDER_COUNT placeholder(s) in README.md"
            
            sed -i "s/DYNAMIC_EMAIL_PLACEHOLDER/$EMAIL/g" README.md
            
            REMAINING_COUNT=$(grep -o "DYNAMIC_EMAIL_PLACEHOLDER" README.md | wc -l || echo "0")
            EMAIL_COUNT=$(grep -o "$EMAIL" README.md | wc -l || echo "0")
            echo "Remaining placeholders: $REMAINING_COUNT"
            echo "Email occurrences after replacement: $EMAIL_COUNT"
            echo "✅ README.md processed successfully"
          else
            echo "❌ README.md not found"
          fi
          
          echo "=== Email replacement completed ==="

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f yarn.lock ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
          else
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**/*.[jt]s','**/*.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
        env:
          CONTACT_EMAIL: ${{ vars.CONTACT_EMAIL }}

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
