name: Update README with Dynamic Content

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README and Contact with dynamic email
        run: |
          # Replace email placeholder with actual email from repository variables
          EMAIL="${{ vars.CONTACT_EMAIL || 'muhammadhaziq341@gmail.com' }}"
          
          # Update README.md
          sed -i "s/DYNAMIC_EMAIL_PLACEHOLDER/$EMAIL/g" README.md
          
          # Update Contact component
          sed -i "s/DYNAMIC_EMAIL_PLACEHOLDER/$EMAIL/g" components/contact.tsx
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md components/contact.tsx
          git diff --staged --quiet || git commit -m "Update README and Contact with dynamic email"
          git push 